#!/bin/bash

usage() { echo -e "With this script you can download csv files from kreport in sugarcrm, if user has permissions." \
    "\nUsage: $0 -h <url-host> -k <kreport id> [-o <output csv file>] [-u <sugar user>] [-p <sugar password>]" \
    "\nfor example: $0 -h https://mysugarcrm.example.com/ -k 00000000-0000-0000-0000-000000000000 -o myreport.csv" \
    "-u user -p mypassword" 1>&2; exit 1; }

while getopts ":h:o:k:u:p:" op; do
    case "${op}" in
        h)
            HOSTNAME_SUGAR=${OPTARG}
            ;;
        o)
            OUTPUT_FILE=${OPTARG}
            ;;
        k)
            KREPORT_ID=${OPTARG}
            ;;
        u)
            SINERGIA_USER=${OPTARG}
            ;;
        p)
            SINERGIA_PASSWORD=${OPTARG}
            ;;
        *)
            usage
            ;;
    esac
done
shift $((OPTIND-1))

if [ -z "${HOSTNAME_SUGAR}" ]; then
    usage
fi

if [ -z "${KREPORT_ID}" ]; then
    usage
fi

# Check url exist
if [ -z "${SINERGIA_USER}" ]; then 
    echo "Please SINERGIA_USER"
    exit  
fi

if [ -z "${SINERGIA_PASSWORD}" ]; then 
    echo "Please SINERGIA_PASSWORD"
    exit  
fi

if [ -z "${OUTPUT_FILE}" ]; then
    OUTPUT_FILE="kreport.csv"
fi


# Descarreguem el fitxer
curl -s ${HOSTNAME_SUGAR}'index.php?action=Login&module=Users&login_module=Home&login_action=index' \
  -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9' \
  -c /tmp/cookies.txt \
  --output /dev/null

curl -s ${HOSTNAME_SUGAR}'index.php' \
  -H 'Content-Type: application/x-www-form-urlencoded' \
  -H 'Referer: '${HOSTNAME_SUGAR}'index.php?action=Login&module=Users&login_module=Home&login_action=index' \
  --data-raw 'module=Users&action=Authenticate&return_module=Users&return_action=Login&cant_login=&login_module=Home&login_action=index&login_record=&login_token=&login_oauth_token=&login_mobile=&login_language=ca_ES&user_name='${SINERGIA_USER}'&user_password='${SINERGIA_PASSWORD}'&Login=Login' \
  -b /tmp/cookies.txt -c /tmp/cookies.txt \
  --output /dev/null

curl -s ${HOSTNAME_SUGAR}'index.php?module=Home&action=index' \
  -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9' \
  -b /tmp/cookies.txt -c /tmp/cookies.txt \
  --output /dev/null

curl ${HOSTNAME_SUGAR}'index.php' \
  -b /tmp/cookies.txt \
  -H 'Content-Type: application/x-www-form-urlencoded' \
  -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36' \
  -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9' \
  -H 'Referer: '${HOSTNAME_SUGAR}'index.php?module=KReports&return_module=KReports&action=DetailView&record='${KREPORT_ID} \
  -H 'Accept-Language: ca-ES,ca;q=0.9' \
  --data-raw 'module=KReports&record='${KREPORT_ID}'&return_action=DetailView&return_module=KReports&return_id=&module_tab=&isDuplicate=false&offset=1&action=export_to_csv&sugar_body_only=&to_pdf=on' \
  --compressed \
  --output ${OUTPUT_FILE}
